### ISSUE TITLE
slick.autocolumnresize.js handleControlKeys() function lacks event parameter

### ISSUE THREAD

**Issue by kayesshu** [naresh-n/slickgrid-column-data-autosize#2]
Hello,
I would like to tell you about a bug I have found in slick.autocolumnresize.js file's handleControlKeys() function misses event parameter, the correct function definition and body should like this:

```
    function handleControlKeys(event) {
    if (event.ctrlKey && event.shiftKey && event.keyCode === keyCodes.A) {
            resizeAllColumns();
        }
    }
```

Hope I could help.
P.S.: Thanks for creating this useful plugin!

**Comment by naresh-n** [comment]
Thank you, added missing event param.
